pcridesagain/2620-fall-23

- Students/Al Baker/buttons.html
- Students/Al Baker/styles.css
Button/Icons Component - Dark Mode
> Fixes UVU-49

- Students/Will Miles/2a.html
- Students/Will Miles/index.html
- Students/Will Miles/styles2a.css
> Fixes UVU-50

- .gitignore
- Students/Diana Putnam/ButtonsAuth-Component-DianaPutnam.html
> ButtonsAuth-DianaP

- Students/Lucy Steckler/style.css
- Students/Lucy Steckler/switches.html
> Initial HTML Component Fixes UVU-39

- Students/Savannah Hilton/index.html
- Students/Savannah Hilton/myFakeIssue.html
- Students/Savannah Hilton/styles.css
> Chips: Pill component - Savannah Hilton

- Students/Ethan Ayers/component.html
- Students/Ethan Ayers/styles.css
> Created segmented bars component

- .gitignore
- Students/Mike Dahle/components.css
- Students/Mike Dahle/components.html
> Fixes UVU-45

- Students/Ho Yin Wong/backdrop.html
- Students/Ho Yin Wong/backdrop2.html
- Students/Ho Yin Wong/styles.css
> Backdrops-Component-Hoyin fixes uvu-59

- Students/Aidan Wiseman/buttons/index.html
- Students/Aidan Wiseman/buttons/style.css
- Students/Aidan Wiseman/index.html
> Fixes UVU-56

- Students/Joonsung Byun/tailwind4/index.html
> First Tailwind Commit

- Students/Will Miles/.gitignore
- Students/Will Miles/Tailwind Component/.gitignore
> William Miles - Tailwind Component UVU-76

- Students/Lucy Steckler/Tailwind Component/index.html
> Lucy-Steckler--Tailwind-Component-UVU-83

- Students/Anferny Mendoza/Tailwind Component/index.html
> Anferny M- Tailwind Component - UVU-82

- Students/Mike Dahle/tailwind-component/index.html
> Mike Dahle - Tailwind Component UVU-85

- .gitignore
- Students/Mason Dietrich/Tailwind Component/index.html
Mason Dietrich Tailwind Component UVU-70
> Resolves UVU-70

- Students/Ethan Ayers/tailwind-component/index.html
> Ethan Ayers - Tailwind Component UVU-69

- Students/Mark Lund/Tailwind Component/index.html
> Mark Lund - Tailwind Component UVU-84

- Students/Ho Yin Wong/Tailwind Component/tailwind.html
> Hoyin-tailwind component-79

- Students/Zachary Stout/Fixes UVU-120
> Create Fixes UVU-120

- Students/Addi Lewis/Tailwind Component/index.html
- Students/Addi Lewis/component.html
> Fixes UVU-112

- .vscode/settings.json
- Students/Ho Yin Wong/Tailwind Component/tailwind.html
> Svelte component UVU-122

- Students/Zachary Stout/Fixes UVU-163
- Students/Zachary Stout/Fixes UVU-163 as well
- Students/Zachary Stout/Fixes UVU-420
import Page from "./Page.svelte";
export default {
title: "Form",
tags: ["autodocs"],
component: Page,
parameters: {
// More on how to position stories at: https://storybook.js.org/docs/svelte/configure/story-layout
layout: "fullscreen",
name: "Select Action",
act1: "Download",
act2: "Save to favorites",
act3: "Comment",
act4: "Share",
act5: "Report this",
},
};
// More on interaction testing: https://storybook.js.org/docs/svelte/writing-tests/interaction-testing
export const Forms = {};
> Create Fixes UVU-163
